const count=document.getElementById("travelerCount"),toast=document.getElementById("toast"),searchButton=document.querySelector(".primary-btn");
const showToast=text=>{toast.textContent=text;toast.classList.add("visible");clearTimeout(window.tt);window.tt=setTimeout(()=>toast.classList.remove("visible"),3000)};
const toIsoDate=date=>{const [day,month,year]=date.split("/");return `${year}-${month}-${day}`};
const money=(amount,currency)=>new Intl.NumberFormat("es-UY",{style:"currency",currency,maximumFractionDigits:0}).format(Number(amount));
function updateProposalCards(offers){document.querySelectorAll(".option").forEach((card,index)=>{const offer=offers[index];if(!offer){card.style.display="none";return}card.style.display="grid";const total=money(offer.totalAmount,offer.totalCurrency),each=money(Number(offer.totalAmount)/Number(count.textContent),offer.totalCurrency);card.querySelector("h3").innerHTML=`${offer.airline}<br>vuelo disponible`;card.querySelector(".option-cost strong").textContent=total;card.querySelector(".option-cost small").textContent=`${each} por persona`;card.querySelectorAll(".real-flight").forEach(item=>item.remove());card.querySelector(".option-cost").insertAdjacentHTML("beforeend",`<small class="real-flight">${offer.duration} · ${offer.connections===0?"Directo":`${offer.connections} escala${offer.connections>1?"s":""}`}</small>`);})}
document.getElementById("minus").onclick=()=>{if(+count.textContent>1)count.textContent=+count.textContent-1};document.getElementById("plus").onclick=()=>count.textContent=+count.textContent+1;
document.querySelectorAll(".travel-types button").forEach(button=>button.onclick=()=>{document.querySelectorAll(".travel-types button").forEach(item=>item.classList.remove("selected"));button.classList.add("selected")});
document.getElementById("tripForm").onsubmit=async event=>{event.preventDefault();const [departureInput,returnInput]=document.querySelectorAll(".grid-two input"),originalLabel=searchButton.innerHTML;searchButton.disabled=true;searchButton.textContent="Buscando vuelos reales…";try{const response=await fetch("/api/flights",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({destination:document.getElementById("destination").value,departureDate:toIsoDate(departureInput.value),returnDate:toIsoDate(returnInput.value),travelers:Number(count.textContent)})}),data=await response.json();if(!response.ok)throw new Error(data.message||"Error de búsqueda");if(!data.offers?.length)throw new Error("No encontramos vuelos para esas fechas.");const first=data.offers[0];document.getElementById("destinationPill").textContent=document.getElementById("destination").value;document.getElementById("travelersInline").textContent=count.textContent;document.querySelector(".total-price").textContent=money(first.totalAmount,first.totalCurrency);document.querySelector(".person-price").textContent=money(Number(first.totalAmount)/Number(count.textContent),first.totalCurrency);document.querySelector(".hero-result h2").innerHTML=`${first.airline}<br>desde Montevideo`;document.querySelector(".hero-result > p").innerHTML=`${first.duration} · ${first.connections===0?"vuelo directo":`${first.connections} escala`}.<br>Precio consultado en Duffel.`;updateProposalCards(data.offers);document.getElementById("results").scrollIntoView({behavior:"smooth"});showToast(`${data.offers.length} vuelos encontrados`)}catch(error){showToast(error.message||"No se pudo buscar vuelos.")}finally{searchButton.disabled=false;searchButton.innerHTML=originalLabel}};
document.querySelectorAll(".option").forEach(card=>card.onclick=()=>{const wasOpen=card.classList.contains("open");document.querySelectorAll(".option").forEach(item=>item.classList.remove("open"));if(!wasOpen)card.classList.add("open")});
document.getElementById("useDates").onclick=()=>{document.querySelector(".grid-two input").value="30/11/2026";document.querySelector(".search-card").scrollIntoView({behavior:"smooth"});showToast("Actualizamos la salida al 30 de noviembre")};
